version: 2

sources:
  - name: retool_jaffle_staging
    database: SE_DEMO_DB
    schema: RETOOL_JAFFLE
    freshness:
        warn_after: {count: 2, period: hour}
        error_after: {count: 4, period: hour}
    loaded_at_field: _etl_loaded_at

    tables:
      - name: stg_customers
      - name: stg_orders
      - name: stg_payments